
apiVersion: v1
kind: Service
metadata:
  name: daytraderee6
  labels:
    app: daytraderee6
spec:
  ports:
    - port: 9080
  selector:
    app: daytraderee6
  type: NodePort

---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  labels:
    app: daytraderee6
  name: daytraderee6
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: daytraderee6
    spec:
      containers:
      - image: mycluster.icp:8500/default/daytraderee6:latest
        name: daytraderee6
        ports:
        - containerPort: 9080
          protocol: TCP
